service: hello
useDotenv: true
provider:
  name: aws
  runtime: nodejs18.x

functions:
  settokens:
    handler: src/handler/set-card.handler
    events:
      - http:
          path: /tokens
          method: post
  gettokens:
    handler: src/handler/get-card.handler
    events:
      - http:
          path: /gettokens
          method: post
custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    target: node18

plugins:
  - serverless-esbuild
  - serverless-offline
