service: hello
useDotenv: true
provider:
  name: aws
  runtime: nodejs18.x

functions:
  cardhandler:
    handler: src/handler/card-handler.handler
    events:
      - http:
          path: /tokens
          method: post
      - http:
          path: /gettokens
          method: post

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    target: node18

plugins:
  - serverless-esbuild
  - serverless-offline
